name: bin-release

on:
  schedule:
    - cron: "4 20 * * *"
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Build
        run: rustup target add x86_64-unknown-linux-gnu && mkdir -p ./build/x86_64-unknown-linux-gnu
      - name: Install coreos-installer with Cargo
        run: cargo install --target x86_64-unknown-linux-gnu --root ./build/x86_64-unknown-linux-gnu coreos-installer
      - name: Strip unneeded
        run: objcopy --strip-unneeded ./build/x86_64-unknown-linux-gnu/bin/coreos-installer
      - name: Compress xz
        run: xz -k ./build/x86_64-unknown-linux-gnu/bin/coreos-installer
      - name: Compress bz2
        run: bzip2 -k ./build/x86_64-unknown-linux-gnu/bin/coreos-installer
      - name: Compress gz
        run: gzip -k ./build/x86_64-unknown-linux-gnu/bin/coreos-installer
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/x86_64-unknown-linux-gnu/bin/*"
          allowUpdates: true
          makeLatest: true
          tag: "latest"
