name: bin-release

on:
  schedule:
    - cron: "4 20 * * *"
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
      volumes:
        - x86_64-unknown-linux-gnu:/build/x86_64-unknown-linux-gnu
    steps:
      - name: verify toolchain
        run: rustup target add x86_64-unknown-linux-gnu
      - name: install coreos-installer with Cargo
        run: cargo install --target x86_64-unknown-linux-gnu --root /build/x86_64-unknown-linux-gnu coreos-installer
      - name: strip unneeded from Binary
        run: objcopy --strip-unneeded /build/x86_64-unknown-linux-gnu/bin/coreos-installer
      - name: compress xz
        run: xz -k /build/x86_64-unknown-linux-gnu/bin/coreos-installer
      - name: compress bz2
        run: bzip2 -k /build/x86_64-unknown-linux-gnu/bin/coreos-installer
      - name: compress gz
        run: gzip -k /build/x86_64-unknown-linux-gnu/bin/coreos-installer
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coreos-installer-artifacts
          path: /build/x86_64-unknown-linux-gnu/bin/*

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: coreos-installer-artifacts
          path: release
      - name: update release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*"
          allowUpdates: true
          makeLatest: true
          tag: "latest"